template: example/template.png
title:
  start:
    px: 123
    pY: 170
  fgHexColor: "#000000"
  fontSize: 70
  fontStyle: Bold
  maxWidth: 946
  lineSpacing: 10
info:
  start:
    px: 227
    py: 441
  fgHexColor: "#8D8D8D"
  fontSize: 38
  fontStyle: Regular
tags:
  start:
    px: 1085
    py: 451
  fgHexColor: "#FFFFFF"
  bgHexColor: "#60BCE0"
  fontSize: 18
  fontStyle: Bold
  boxAlign: Right
  boxSpacing: 6
  boxPadding:
    top: 6
    right: 10
    bottom: 6
    left: 10
